name: Pathogenic Action Initiator
description: Compare the current commit with the previous successful commit and return a single boolean value. Does nothing else.
author: khongchai

inputs:
  paths:
    description: "The paths to check for changes. Supports glob patterns."
    required: true
  github_token:
    description: "The GitHub token to use for authentication."
    required: true
outputs:
  changed:
    description: "A boolean value indicating whether any of the paths have changed."

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.paths }}
