name: latest-successful-job-run
description: Return the latest successful job run SHA for a given job name within a workflow of the current branch.
author: khongchai

inputs:
  job:
    description: "The name of the job to check for."
    required: true
outputs:
  sha:
    description: "The SHA of the previous successful commit in which the specified job was successful"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.job }}
