name: latest-successful-job-run
description: Return the latest successful job run SHA for a given job name within a workflow of the current branch.
author: khongchai

inputs:
  # https://github.com/orgs/community/discussions/8945 cannot use job id :\
  job:
    description: "The name of the job to check for."
    required: true
  token:
    description: "The GitHub token to use for authentication."
    required: true
outputs:
  sha:
    description: "The SHA of the previous successful commit in which the specified job was successful"

runs:
  using: "node16"
  main: "dist/index.js"
