# Just a draft of what I think the final API (the yaml file) should look like
name: CI

on:
  workflow_call:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Run if any file(s) change
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # This will compare the current commit with any previous commit that contains a successful specified job.
      - name: Get all changed files in frontend folders
        id: prev-successful-changed-files
        uses: khongchai/pathogenic-action-intiator
        with:
          job-name: chromatic-ci
          paths: |
            frontend/src/**/*
            packages/ui/src/**/*

      # Run your action, for example, publish your storybook to chromatic
      - name: Run your action
        if: steps.prev-successful-changed-files.outputs.changed == 'true'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: docs
